packaging_format = 2

id = "2fauth"
name = "2FAuth"
description.en = "self-hosted alternative to One Time Passcode"
description.fr = "Alternative auto-hébergée a One Time Passcode"

version = "4.0.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://demo.2fauth.app/login"
admindoc = "https://docs.2fauth.app/"
code = "https://github.com/Bubka/2FAuth"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Bubka/2FAuth/archive/refs/tags/v4.0.3.tar.gz"
        sha256 = "d9c680bd79d3143c27e2ca22dba15e59ed8b10ee33586e84497b621fdfeb56cc"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.1-bcmath php8.1-xml php8.1-mbstring php8.1-gd php8.1-mysql php8.1-curl"

    [resources.database]
    type = "mysql"
