packaging_format = 2

id = "2fauth"
name = "2FAuth"
description.en = "self-hosted alternative to One Time Passcode"
description.fr = "Alternative auto-hébergée a One Time Passcode"

version = "3.4.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://demo.2fauth.app/login"
admindoc = "https://docs.2fauth.app/"
code = "https://github.com/Bubka/2FAuth"
website = "https://github.com/Bubka/2FAuth"

[integration]
yunohost = ">= 11.1.7"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "mysql"
